/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package usuarios;
import Objetos.ImagenMySQL;
import Objetos.ModelitoSocio;
import codigo.ConsultasCrud;
import java.applet.*;
import java.awt.image.BufferedImage;
import java.beans.PropertyVetoException;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import socepapp.INICIO;
import utilidades.configuracionXml;
/**
 *
 * @author Acer
 */
public class UsuariosSocio extends javax.swing.JInternalFrame {
    configuracionXml config = new configuracionXml();
    ConsultasCrud crud = new ConsultasCrud( config.getConexion().getConexion());
    String tabla = "socios";
    String campos = "socios.Nombre";
    String filaNombre;
    
    ModelitoSocio info = new ModelitoSocio();
    
    
    /**
     * Creates new form UsuariosSocio
     */
    public UsuariosSocio() {
        initComponents();
        mostrar_articulos();
        ListaSocios.setSelectedIndex(0);
        seleccionearItem();
    }
    
//    public UsuariosSocio(ModelitoSocio mod) {
//        this.mod = mod;
//        initComponents();
//        mostrar_articulos();
//        ListaSocios.setSelectedIndex(0);
//        seleccionearItem();
//    }
    
    public void mostrar_articulos(){
        try {
            DefaultListModel modeloLista = new DefaultListModel();
            modeloLista = crud.listas(tabla, campos);
            ListaSocios.setModel(modeloLista);
        } catch (SQLException ex) {
            Logger.getLogger(UsuarioProductos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void seleccionearItem(){
        int fila = ListaSocios.getSelectedIndex();
        if(fila >= 0){
            DefaultListModel NuevoModeloLista = (DefaultListModel) ListaSocios.getModel();
            filaNombre = NuevoModeloLista.getElementAt(fila).toString();
            selecionaImagenActualiza(filaNombre);
            LabelNombre.setText("Nombre: "+filaNombre);
            info.setNombre(filaNombre);
            pantallaProductoUsuario();
        }
    }
    
    public void selecionaImagenActualiza(String res){
        PreparedStatement ps;
        ResultSet rs;
        PanelImagen.removeAll();
        PanelImagen.repaint();

        try {
            Connection con =  config.getConexion().getConexion();
            ps = con.prepareStatement("SELECT logo FROM socios WHERE socios.Nombre=?");
            ps.setString(1, res);
            rs = ps.executeQuery();

            BufferedImage buffimg = null;
            byte[] image = null;
            while (rs.next()) {
                image = rs.getBytes("logo");
                InputStream img = rs.getBinaryStream(1);
                try {
                    buffimg = ImageIO.read(img);
                    ImagenMySQL imagen = new ImagenMySQL(165, 121, buffimg);
                    PanelImagen.add(imagen);
                    PanelImagen.repaint();
                } catch (IOException ex) {
                    Logger.getLogger(UsuarioProductos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            rs.close();
        } catch (SQLException ex) {
            System.err.println(ex.toString());
        }
    }
    
    public void pantallaProductoUsuario() {
    try {
      //habrimos la pantalla de clientes
      //String grupo = jLabel3.getText();
      boolean b = true;
      detallesSocios UP = new detallesSocios(info);
      this.EscritorioSocio.removeAll();
      this.EscritorioSocio.repaint();
      this.EscritorioSocio.add(UP);
      UP.setMaximum(b);
      UP.setVisible(true);  

    } catch (PropertyVetoException ex) {
      Logger.getLogger(INICIO.class.getName()).log(Level.SEVERE, null, ex);
    }
   
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaSocios = new javax.swing.JList<>();
        PanelImagen = new javax.swing.JPanel();
        LabelNombre = new javax.swing.JLabel();
        EscritorioSocio = new javax.swing.JDesktopPane();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        ListaSocios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ListaSocios.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Coperativa 1", "Coperativa 2", "Coperativa 3", "Coperativa 4", "Coperativa 5", "Coperativa 6" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ListaSocios.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ListaSocios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaSociosMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ListaSociosMouseReleased(evt);
            }
        });
        ListaSocios.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ListaSociosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(ListaSocios);

        PanelImagen.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout PanelImagenLayout = new javax.swing.GroupLayout(PanelImagen);
        PanelImagen.setLayout(PanelImagenLayout);
        PanelImagenLayout.setHorizontalGroup(
            PanelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 165, Short.MAX_VALUE)
        );
        PanelImagenLayout.setVerticalGroup(
            PanelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        LabelNombre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LabelNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelNombre.setText("Coperativa: nombre de la coperativa");

        javax.swing.GroupLayout EscritorioSocioLayout = new javax.swing.GroupLayout(EscritorioSocio);
        EscritorioSocio.setLayout(EscritorioSocioLayout);
        EscritorioSocioLayout.setHorizontalGroup(
            EscritorioSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        EscritorioSocioLayout.setVerticalGroup(
            EscritorioSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 382, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EscritorioSocio)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 45, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EscritorioSocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(LabelNombre, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(PanelImagen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListaSociosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaSociosMouseClicked
        seleccionearItem();
    }//GEN-LAST:event_ListaSociosMouseClicked

    private void ListaSociosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaSociosMouseReleased
        seleccionearItem();
    }//GEN-LAST:event_ListaSociosMouseReleased

    private void ListaSociosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ListaSociosValueChanged
        seleccionearItem();
    }//GEN-LAST:event_ListaSociosValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane EscritorioSocio;
    private javax.swing.JLabel LabelNombre;
    private javax.swing.JList<String> ListaSocios;
    private javax.swing.JPanel PanelImagen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
